// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Persistence;

namespace backend.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20201023155405_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("backend.Persistence.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            CreatedOn = new DateTime(2015, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentID = 2,
                            CreatedOn = new DateTime(2015, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Audit"
                        },
                        new
                        {
                            DepartmentID = 3,
                            CreatedOn = new DateTime(2015, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Accounts"
                        },
                        new
                        {
                            DepartmentID = 4,
                            CreatedOn = new DateTime(2015, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "HR"
                        },
                        new
                        {
                            DepartmentID = 5,
                            CreatedOn = new DateTime(2015, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Marketing"
                        });
                });

            modelBuilder.Entity("backend.Persistence.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DOJ")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            DOB = new DateTime(2000, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOJ = new DateTime(2015, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            EmployeeName = "Karl Reit",
                            Gender = "Male"
                        },
                        new
                        {
                            EmployeeID = 2,
                            DOB = new DateTime(1995, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOJ = new DateTime(2015, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            EmployeeName = "Catty Floyd",
                            Gender = "Female"
                        },
                        new
                        {
                            EmployeeID = 3,
                            DOB = new DateTime(1995, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOJ = new DateTime(2015, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            EmployeeName = "Jimmy Trudeau",
                            Gender = "Male"
                        },
                        new
                        {
                            EmployeeID = 4,
                            DOB = new DateTime(1997, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOJ = new DateTime(2015, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            EmployeeName = "Linda Oltah",
                            Gender = "Female"
                        },
                        new
                        {
                            EmployeeID = 5,
                            DOB = new DateTime(2003, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOJ = new DateTime(2015, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            EmployeeName = "Steven Reeves",
                            Gender = "Male"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
